// https://developers.google.com/maps/faq#languagesupport
export enum GOOGLE_LANGUAGE_CODES_ENUM {
  af = "af", // Africâner
  ja = "ja", // Japonês
  sq = "sq", // Albanês
  kn = "kn", // Kannada
  am = "am", // Amárico
  kk = "kk", // Cazaque
  ar = "ar", // Árabe
  km = "km", // Khmer
  hy = "hy", // Armênio
  ko = "ko", // Coreano
  az = "az", // Azerbaijano
  ky = "ky", // Quirguiz
  eu = "eu", // Basco
  lo = "lo", // Laosiano
  be = "be", // Bielorrusso
  lv = "lv", // Letão
  bn = "bn", // Bengali
  lt = "lt", // Lituano
  bs = "bs", // Bósnio
  mk = "mk", // Macedônio
  bg = "bg", // Búlgaro
  ms = "ms", // Malaio
  my = "my", // Birmanês
  ml = "ml", // Malaiala
  ca = "ca", // Catalão
  mr = "mr", // Marata
  zh = "zh", // Chinês
  mn = "mn", // Mongol
  "zh-CN" = "zh-CN", // Chinês (simplificado)
  ne = "ne", // Nepalês
  "zh-HK" = "zh-HK", // Chinês (Hong Kong)
  no = "no", // Norueguês
  "zh-TW" = "zh-TW", // Chinês (tradicional)
  pl = "pl", // Polonês
  hr = "hr", // Croata
  pt = "pt", // Português
  cs = "cs", // Tcheco
  "pt-BR" = "pt-BR", // Português (Brasil)
  da = "da", // Dinamarquês
  "pt-PT" = "pt-PT", // Português (Portugal)
  nl = "nl", // Holandês
  pa = "pa", // Punjabi
  en = "en", // Inglês
  ro = "ro", // Romeno
  "en-AU" = "en-AU", // Inglês (Austrália)
  ru = "ru", // Russa
  "en-GB" = "en-GB", // Inglês (Reino Unido)
  sr = "sr", // Sérvio
  et = "et", // Estoniano
  si = "si", // Cingalês
  fa = "fa", // Farsi
  sk = "sk", // Eslovaco
  fi = "fi", // Finlandês
  sl = "sl", // Esloveno
  fil = "fil", // Filipino
  es = "es", // Espanhol
  fr = "fr", // Francês
  "es-419" = "es-419", // Espanhol (América Latina)
  "fr-CA" = "fr-CA", // Francês (Canadá)
  sw = "sw", // Suaíli
  gl = "gl", // Galego
  sv = "sv", // Sueco
  ka = "ka", // Georgiano
  ta = "ta", // Tâmil
  de = "de", // Alemão
  te = "te", // Télugo
  el = "el", // Grego
  th = "th", // Tailandês
  gu = "gu", // Guzerate
  tr = "tr", // Turco
  iw = "iw", // Hebraico
  uk = "uk", // Ucraniano
  hi = "hi", // Híndi
  ur = "ur", // Urdu
  hu = "hu", // Húngaro
  uz = "uz", // Uzbeque
  is = "is", // Islandês
  vi = "vi", // Vietnamita
  id = "id", // Indonésio
  zu = "zu", // Zulu
  it = "it", // Italiano
}
