version: "3.9"

services:
  cherry-go-api:
    image: "node"
    container_name: cherry-go-api
    command: sh -c "yarn && yarn start:dev"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "3333:3333"
      - "9231:9229"
    depends_on:
      - database-postgres
      - database-mongo
      - database-redis

  database-postgres:
    image: postgres
    container_name: database-pg
    ports:
      - 5432:5432
    # environment:
      # - POSTGRES_USER==${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres

  database-mongo:
    image: mongo
    container_name: database-mongo
    ports:
      - 27017:27017
    volumes:
      - pgmongo:/data/mongo

  database-redis:
    image: redis:alpine
    container_name: database-redis
    ports:
      - 6379:6379
    volumes:
      - pgredis:/data/redis

volumes:
  pgdata:
    driver: local
  pgredis:
    driver: local
  pgmongo:
    driver: local
