:database-postgres
  docker-compose up -d database_postgres
.PHONY:database-postgres

:database-mongo
  docker-compose up -d database_mongo
.PHONY:database-mongo

:database-redis
  docker-compose up -d database_redis
.PHONY:database-redis

:kafka
  docker-compose -f .\apache-kafka\docker-compose.yaml
.PHONY:kafka

:make down
  docker-compose -f .\apache-kafka\docker-compose.yaml down && docker-compose down
.PHONY:down

all-local:database-postgres database-mongo database-redis kafka
.PHONY: all-local
