export enum TYPE_USER_TOKEN_ENUM {
  PHONE_CONFIRMATION = "PHONE_CONFIRMATION",
  AUTH_SESSION_TOKEN = "AUTH_SESSION_TOKEN",
  AUTH_SESSION_REFRESH_TOKEN = "AUTH_SESSION_REFRESH_TOKEN",
  CREATE_USER_CLIENT = "CREATE_USER_CLIENT",
  CREATE_USER_PROVIDER = "CREATE_USER_PROVIDER",
  CREATE_USER_INSIDER = "CREATE_USER_INSIDER",
  EMAIL_CONFIRMATION = "EMAIL_CONFIRMATION",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
}
